# .github/workflows/publish.yml
name: Publish Blog to Medium (Selenium)

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          pip install -r requirement.txt

      - name: Run Blog Agent Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          MEDIUM_USERNAME: ${{ secrets.MEDIUM_USER }}
          MEDIUM_PASSWORD: ${{ secrets.MEDIUM_PASS }}
        run: xvfb-run python main.py