
name: Auto Publish Blog to Medium

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set environment
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run blog pipeline
        run: python main.py
